支持处理包含多个视频流的MKV文件
KJH-x/scans_creator pull request #3
Opened 2024-11-13 12:42 UTC by fishyy119

对于.mkv文件，其实际上可能包含多个视频流。此提交增加了对含有多视频流的文件的支持，可以选择用于输出的视频流。

2024-11-13 16:25 UTC, KJH-x commented on VideoInfo.py
> +            return False
应该为如 `raise IndexError(f"{index} is not available")`

2024-11-13 16:31 UTC, KJH-x commented on VideoInfo.py
> +        self.number_of_video_streams : int = len(video_streams)
此`self.number_of_video_streams` 为仅变换一次的内部变量，没有进一步作用，应排除结构体，在外部用`len(self.video_streams)`完成

2024-11-13 16:34 UTC, KJH-x commented on scan_creator.py
> +            if video_info.number_of_video_streams > 1:
改为：`if (video_stream_count:=len(video_info.video_streams)) >1` ,后续用`video_stream_count`替换

2024-11-13 16:45 UTC, KJH-x commented on scan_creator.py
> +
条件重复：过多的index判断：此`while` 改为 `while True, break` 的结构即可，将`set_active_video_stream`放入`try-except`内，通过处理`index error`来处理异常输入

另外 line 590的else似乎缩进是错误的，没有看懂此处的逻辑，
且处理视频流不大于1的情况时，selected_stream_index 应始终为`0`, 且无需打印信息

2024-11-13 16:46 UTC, KJH-x requested changes
本pull request 中的问题已描述，请做修改后再提交

2024-11-14 00:38 UTC, fishyy119 commented on scan_creator.py
> +
当while通过判断条件为假退出时，会执行对应的else内部语句，其他方式退出（break等）则不执行；

仅在视频流数量大于1时，才会有这些输出。

此处已改为while True break结构。

2024-11-14 04:37 UTC, merged